<a href="https://colab.research.google.com/github/SindhuraShankeshi/colab/blob/main/AdvancedTF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import tensorflow as tf

In [14]:
a=tf.range(15)
a

<tf.Tensor: shape=(15,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
      dtype=int32)>

In [15]:
tf.reshape(a,[3,5])

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]], dtype=int32)>

In [16]:
x = tf.random.normal([4,10])

In [27]:
tf.reduce_max(x,axis=0) 

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([2.0753412 , 0.30130193, 0.72336966, 0.51583815, 1.1947258 ,
       0.70528424, 0.49665222, 1.305292  , 0.16228004, 1.4340054 ],
      dtype=float32)>

In [17]:
tf.reduce_max(x,axis=1) # get maximum value at 2nd dimesnion

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.5125163, 1.9133053, 1.042583 , 1.9902619], dtype=float32)>

In [18]:
 tf.reduce_min(x,axis=1)  # get the minimum value at 2nd dimension

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-0.88267905, -1.0319763 , -1.3986382 , -1.5898691 ], dtype=float32)>

In [22]:
tf.reduce_min(x,axis=0) #minimum value at 1st dimension

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-1.5525501 , -1.2204634 , -3.2556183 , -0.6139832 , -0.9638279 ,
       -1.0341225 , -1.3214713 ,  0.46418652, -1.28487   , -1.6405026 ],
      dtype=float32)>

In [19]:
tf.reduce_min(a)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [20]:
#Find the mean probabilities of each sample:
tf.reduce_mean(x,axis=1)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.21462473, 0.00155795, 0.17218515, 0.3362556 ], dtype=float32)>

In [23]:
tf.reduce_mean(x,axis=0)

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([ 0.35925218, -0.3919202 , -1.1717557 , -0.29018694, -0.13167042,
       -0.36847025, -0.4087186 ,  0.7481887 , -0.5017662 , -0.21186578],
      dtype=float32)>

In [21]:
#When the axis parameter is not specified, the tf.reduce_* functions will 
# find the maximum, minimum, mean, and sum of all the data:
x = tf.random.normal([4,10])
tf.reduce_max(x),tf.reduce_min(x),tf.reduce_mean(x)

(<tf.Tensor: shape=(), dtype=float32, numpy=2.0753412>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-3.2556183>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-0.23689131>)