<a href="https://colab.research.google.com/github/SindhuraShankeshi/colab/blob/main/AdvancedTF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
a=tf.range(15)
a

<tf.Tensor: shape=(15,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
      dtype=int32)>

In [ ]:
tf.reshape(a,[3,5])

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]], dtype=int32)>

In [ ]:
x = tf.random.normal([4,10])

In [ ]:
tf.reduce_max(x,axis=0) 

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([2.0753412 , 0.30130193, 0.72336966, 0.51583815, 1.1947258 ,
       0.70528424, 0.49665222, 1.305292  , 0.16228004, 1.4340054 ],
      dtype=float32)>

In [ ]:
tf.reduce_max(x,axis=1) # get maximum value at 2nd dimesnion

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.5125163, 1.9133053, 1.042583 , 1.9902619], dtype=float32)>

In [ ]:
 tf.reduce_min(x,axis=1)  # get the minimum value at 2nd dimension

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-0.88267905, -1.0319763 , -1.3986382 , -1.5898691 ], dtype=float32)>

In [ ]:
tf.reduce_min(x,axis=0) #minimum value at 1st dimension

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-1.5525501 , -1.2204634 , -3.2556183 , -0.6139832 , -0.9638279 ,
       -1.0341225 , -1.3214713 ,  0.46418652, -1.28487   , -1.6405026 ],
      dtype=float32)>

In [ ]:
tf.reduce_min(a)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [ ]:
#Find the mean probabilities of each sample:
tf.reduce_mean(x,axis=1)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.21462473, 0.00155795, 0.17218515, 0.3362556 ], dtype=float32)>

In [ ]:
tf.reduce_mean(x,axis=0)

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([ 0.35925218, -0.3919202 , -1.1717557 , -0.29018694, -0.13167042,
       -0.36847025, -0.4087186 ,  0.7481887 , -0.5017662 , -0.21186578],
      dtype=float32)>

In [ ]:
#When the axis parameter is not specified, the tf.reduce_* functions will 
# find the maximum, minimum, mean, and sum of all the data:
x = tf.random.normal([4,10])
tf.reduce_max(x),tf.reduce_min(x),tf.reduce_mean(x)

(<tf.Tensor: shape=(), dtype=float32, numpy=2.0753412>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-3.2556183>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-0.23689131>)

In [ ]:
#TENSOR COMPARISION
#Function Comparison logic:
# tf.math.greater   a > b
# tf.math.less   a < b
# tf.math.greater_equal   a ≥ b
# tf.math.less_equal   a ≤ b
# tf.math.not_equal   a ≠ b
# tf.math.is_nan   a = nan

In [2]:
import tensorflow as tf

In [3]:
out=tf.random.normal([100,10])
out

<tf.Tensor: shape=(100, 10), dtype=float32, numpy=
array([[ 6.49261653e-01,  1.00383413e+00,  9.49151993e-01,
         8.77103135e-02,  3.09690565e-01,  9.21286881e-01,
         6.39576852e-01, -1.16615169e-01,  1.68188304e-01,
        -1.11947417e+00],
       [-7.91723371e-01, -8.09855044e-01,  6.33973718e-01,
         1.50373787e-01, -2.02116704e+00, -3.68488461e-01,
        -1.57646585e+00,  5.74373960e-01,  2.43898053e-02,
         7.28408456e-01],
       [ 1.37768996e+00, -7.07184851e-01, -1.98222983e+00,
         6.16540372e-01, -9.50579345e-02, -6.18231893e-01,
         1.67036128e+00, -2.18123531e+00,  3.26294214e-01,
         2.64748216e+00],
       [-1.64831960e+00,  1.89064100e-01,  1.19715071e+00,
         1.85328054e+00,  1.05782795e+00, -1.59095049e+00,
         1.08721778e-01, -5.73258817e-01,  5.57365656e-01,
        -8.68598700e-01],
       [-7.97405422e-01,  1.15983224e+00,  1.25589776e+00,
         1.91113591e+00, -2.44253254e+00,  5.55203855e-01,
         5.00055492

In [4]:
out = tf.nn.softmax(out, axis=1) # Convert to probability
out

<tf.Tensor: shape=(100, 10), dtype=float32, numpy=
array([[0.11608661, 0.16548972, 0.15668336, 0.06620694, 0.08266246,
        0.15237762, 0.11496776, 0.0539717 , 0.07175541, 0.0197984 ],
       [0.04600181, 0.04517524, 0.19140239, 0.11801103, 0.01345347,
        0.07023985, 0.02098773, 0.18032813, 0.10404193, 0.21035838],
       [0.13756281, 0.01710218, 0.00477866, 0.0642596 , 0.0315424 ,
        0.01869318, 0.18433447, 0.00391633, 0.04807127, 0.4897391 ],
       [0.0106756 , 0.06704371, 0.18372339, 0.35409355, 0.15982965,
        0.01130596, 0.06186796, 0.03128134, 0.09689678, 0.02328203],
       [0.02166357, 0.15337254, 0.1688373 , 0.32511324, 0.00418081,
        0.08378395, 0.07928851, 0.0628667 , 0.02377915, 0.07711427],
       [0.03681592, 0.1169622 , 0.07039701, 0.04978896, 0.27236676,
        0.13698858, 0.11762069, 0.09668289, 0.05722406, 0.04515295],
       [0.02253768, 0.05877009, 0.29119292, 0.11458708, 0.26531738,
        0.03050004, 0.04008225, 0.01796208, 0.01701315, 0.1

In [5]:
pred = tf.argmax(out, axis=1) # Find corresponding category
pred

<tf.Tensor: shape=(100,), dtype=int64, numpy=
array([1, 9, 9, 3, 3, 4, 2, 5, 3, 2, 5, 1, 4, 4, 9, 1, 4, 8, 2, 8, 0, 6,
       6, 3, 4, 9, 4, 9, 9, 0, 3, 1, 5, 1, 0, 9, 3, 1, 6, 2, 7, 8, 8, 1,
       3, 9, 7, 7, 7, 4, 8, 8, 2, 8, 2, 8, 0, 1, 0, 3, 9, 6, 6, 3, 9, 2,
       1, 3, 3, 6, 7, 3, 2, 3, 0, 4, 5, 4, 9, 4, 9, 9, 7, 4, 9, 9, 4, 6,
       0, 6, 9, 7, 7, 5, 9, 9, 3, 2, 2, 8])>

In [7]:
# Simiulate the true labels
y = tf.random.uniform([100],dtype=tf.int64,maxval=10)
y

<tf.Tensor: shape=(100,), dtype=int64, numpy=
array([9, 1, 4, 5, 9, 2, 5, 5, 9, 0, 6, 8, 6, 1, 4, 9, 1, 4, 5, 2, 0, 4,
       3, 4, 5, 2, 3, 8, 7, 4, 5, 2, 0, 1, 8, 8, 3, 1, 2, 8, 0, 6, 8, 4,
       7, 7, 4, 0, 2, 5, 0, 6, 3, 3, 9, 7, 4, 0, 9, 9, 6, 4, 9, 3, 6, 8,
       7, 0, 6, 3, 9, 5, 6, 7, 0, 9, 8, 9, 6, 4, 1, 4, 6, 1, 4, 7, 7, 9,
       8, 2, 8, 6, 3, 4, 1, 2, 0, 7, 4, 7])>

In [8]:
out = tf.equal(pred,y) # Compare true and prediction
out

<tf.Tensor: shape=(100,), dtype=bool, numpy=
array([False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
        True,  True, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])>

In [14]:
out = tf.cast(out, dtype=tf.float32) # convert to int type
correct = tf.reduce_sum(out) # get the number of True element
correct

<tf.Tensor: shape=(), dtype=float32, numpy=9.0>

In [9]:
g = tf.math.greater(pred,y)
g

<tf.Tensor: shape=(100,), dtype=bool, numpy=
array([False,  True,  True, False, False,  True, False, False, False,
        True, False, False, False,  True,  True, False,  True,  True,
       False,  True, False,  True,  True, False, False,  True,  True,
        True,  True, False, False, False,  True, False, False,  True,
       False, False,  True, False,  True,  True, False, False, False,
        True,  True,  True,  True, False,  True,  True, False,  True,
       False,  True, False,  True, False, False,  True,  True, False,
       False,  True, False, False,  True, False,  True, False, False,
       False, False, False, False, False, False,  True, False,  True,
        True,  True,  True,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
        True])>

In [10]:
l = tf.math.less(pred,y)
l

<tf.Tensor: shape=(100,), dtype=bool, numpy=
array([ True, False, False,  True,  True, False,  True, False,  True,
       False,  True,  True,  True, False, False,  True, False, False,
        True, False, False, False, False,  True,  True, False, False,
       False, False,  True,  True,  True, False, False,  True, False,
       False, False, False,  True, False, False, False,  True,  True,
       False, False, False, False,  True, False, False,  True, False,
        True, False,  True, False,  True,  True, False, False,  True,
       False, False,  True,  True, False,  True, False,  True,  True,
        True,  True, False,  True,  True,  True, False, False, False,
       False, False, False, False, False,  True,  True,  True, False,
       False, False, False, False, False, False, False,  True,  True,
       False])>

In [11]:
ge = tf.math.greater_equal(pred,y)
ge

<tf.Tensor: shape=(100,), dtype=bool, numpy=
array([False,  True,  True, False, False,  True, False,  True, False,
        True, False, False, False,  True,  True, False,  True,  True,
       False,  True,  True,  True,  True, False, False,  True,  True,
        True,  True, False, False, False,  True,  True, False,  True,
        True,  True,  True, False,  True,  True,  True, False, False,
        True,  True,  True,  True, False,  True,  True, False,  True,
       False,  True, False,  True, False, False,  True,  True, False,
        True,  True, False, False,  True, False,  True, False, False,
       False, False,  True, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
        True])>

In [12]:
ne = tf.not_equal(pred,y)
ne

<tf.Tensor: shape=(100,), dtype=bool, numpy=
array([ True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
       False, False,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])>