<a href="https://colab.research.google.com/github/SindhuraShankeshi/colab/blob/main/Fill%26CopyTF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
a = tf.constant([1,2,3,4,5,6]) # 1st sentence
b = tf.constant([7,8,1,6]) # 2nd sentence
b = tf.pad(b, [[0,2]]) # Pad two 0's in the end of 2nd sentence
b

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([7, 8, 1, 6, 0, 0], dtype=int32)>

In [3]:
tf.stack([a,b],axis=0) # Stack a and b

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[1, 2, 3, 4, 5, 6],
       [7, 8, 1, 6, 0, 0]], dtype=int32)>

In [5]:
x = tf.random.normal([4,32,32,3])
x

<tf.Tensor: shape=(4, 32, 32, 3), dtype=float32, numpy=
array([[[[-1.13637400e+00,  6.42299354e-01,  5.60377203e-02],
         [-8.06303769e-02, -1.03297316e-01, -1.40288758e+00],
         [-3.15550148e-01,  6.00339115e-01,  2.32844561e-01],
         ...,
         [-5.19270837e-01, -2.57380754e-02,  2.21982527e+00],
         [ 8.68159235e-01,  8.15286398e-01, -1.31409299e+00],
         [ 1.05674815e+00, -3.74119908e-01,  2.26975188e-01]],

        [[ 1.06025279e+00,  1.37192714e+00, -1.23280513e+00],
         [-2.84235507e-01,  1.21989644e+00, -7.98097610e-01],
         [ 2.16492951e-01, -2.14259696e+00, -1.78562319e+00],
         ...,
         [ 1.49868214e+00, -2.41820276e-01, -1.41465092e+00],
         [-9.48134720e-01,  3.17903250e-01,  3.83206457e-02],
         [-4.05446023e-01,  6.69659853e-01,  8.74100178e-02]],

        [[ 2.06857845e-01,  1.40496129e-02, -7.33284116e-01],
         [ 8.80963743e-01, -2.11941376e-01, -4.31201339e-01],
         [ 1.12582707e+00,  1.67348817e-01, 

In [6]:
tf.tile(x,[2,3,3,1])

<tf.Tensor: shape=(8, 96, 96, 3), dtype=float32, numpy=
array([[[[-1.13637400e+00,  6.42299354e-01,  5.60377203e-02],
         [-8.06303769e-02, -1.03297316e-01, -1.40288758e+00],
         [-3.15550148e-01,  6.00339115e-01,  2.32844561e-01],
         ...,
         [-5.19270837e-01, -2.57380754e-02,  2.21982527e+00],
         [ 8.68159235e-01,  8.15286398e-01, -1.31409299e+00],
         [ 1.05674815e+00, -3.74119908e-01,  2.26975188e-01]],

        [[ 1.06025279e+00,  1.37192714e+00, -1.23280513e+00],
         [-2.84235507e-01,  1.21989644e+00, -7.98097610e-01],
         [ 2.16492951e-01, -2.14259696e+00, -1.78562319e+00],
         ...,
         [ 1.49868214e+00, -2.41820276e-01, -1.41465092e+00],
         [-9.48134720e-01,  3.17903250e-01,  3.83206457e-02],
         [-4.05446023e-01,  6.69659853e-01,  8.74100178e-02]],

        [[ 2.06857845e-01,  1.40496129e-02, -7.33284116e-01],
         [ 8.80963743e-01, -2.11941376e-01, -4.31201339e-01],
         [ 1.12582707e+00,  1.67348817e-01, 

In [7]:
x = tf.range(9)
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [8]:
tf.maximum(x,2) 

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([2, 2, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [9]:
tf.minimum(x,7)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 7], dtype=int32)>

In [10]:
#Advanced Operations
#tf.gather
x = tf.random.uniform([4,35,8],maxval=100,dtype=tf.int32)
x

<tf.Tensor: shape=(4, 35, 8), dtype=int32, numpy=
array([[[90, 87,  9, ..., 12, 73, 71],
        [62, 96, 17, ..., 84, 79,  1],
        [11, 95, 73, ..., 29, 37, 84],
        ...,
        [67, 78, 81, ..., 78, 42, 37],
        [76, 16, 58, ..., 19, 80, 63],
        [ 9, 84, 13, ..., 80, 74, 50]],

       [[99, 88, 75, ..., 39, 57, 61],
        [86, 73,  8, ..., 34, 58, 49],
        [14, 69, 90, ..., 42, 45, 96],
        ...,
        [15, 73, 43, ...,  5,  6,  3],
        [86, 94, 50, ..., 21,  1, 20],
        [ 5, 65, 29, ...,  7, 11,  4]],

       [[ 1, 11, 23, ..., 33, 98, 73],
        [20,  0, 62, ..., 99, 87, 45],
        [61, 54, 28, ...,  9, 38, 38],
        ...,
        [ 7, 22, 62, ..., 69, 42, 97],
        [38, 44, 83, ..., 55, 65, 73],
        [46, 58, 88, ..., 44, 44, 71]],

       [[57, 10, 73, ..., 80, 84, 34],
        [26, 28, 25, ...,  7, 36, 96],
        [37, 90, 94, ..., 95, 95, 89],
        ...,
        [26,  0,  2, ..., 23, 61, 11],
        [62, 38, 89, ..., 76, 80, 

In [11]:
tf.gather(x,[0,1],axis=0) # Collect data for 1st and 2nd classes

<tf.Tensor: shape=(2, 35, 8), dtype=int32, numpy=
array([[[90, 87,  9, 23, 10, 12, 73, 71],
        [62, 96, 17, 42, 94, 84, 79,  1],
        [11, 95, 73, 40, 45, 29, 37, 84],
        [70, 15, 67, 39, 33, 34, 12, 31],
        [46, 38, 92, 89, 53,  3,  3, 28],
        [32, 46, 34, 83, 89, 11, 61, 29],
        [19, 51, 26, 13, 54, 31,  1, 88],
        [83, 63, 19, 55, 99, 66, 35, 88],
        [31, 46, 85, 58,  0, 63, 10, 58],
        [18, 91, 99, 61, 41, 25, 40,  1],
        [ 9, 25,  1, 78, 75,  6,  8, 47],
        [19, 48, 76, 65, 60, 34, 23, 37],
        [13, 34, 32,  6, 12, 53, 96, 54],
        [84, 94, 26, 50, 64, 37, 86, 17],
        [13, 35,  9,  8, 10, 62,  7, 99],
        [89, 80, 62, 28, 55, 67, 18, 45],
        [91, 96, 60, 44, 13, 53, 72, 61],
        [60, 74, 56, 57, 50,  5, 80, 98],
        [86, 67, 54, 63, 18, 86,  9, 52],
        [18, 40, 65, 65, 98, 56, 78, 17],
        [25, 10, 13, 67, 72, 16, 67, 83],
        [63, 37, 80, 42, 75, 25, 17, 65],
        [21, 41,  2, 95, 5

In [12]:
 # Collect the grade of students 1,4,9,12,13 and 27
tf.gather(x,[0,3,8,11,12,26],axis=1)

<tf.Tensor: shape=(4, 6, 8), dtype=int32, numpy=
array([[[90, 87,  9, 23, 10, 12, 73, 71],
        [70, 15, 67, 39, 33, 34, 12, 31],
        [31, 46, 85, 58,  0, 63, 10, 58],
        [19, 48, 76, 65, 60, 34, 23, 37],
        [13, 34, 32,  6, 12, 53, 96, 54],
        [95, 77, 42, 79, 22, 77, 53, 58]],

       [[99, 88, 75, 19, 50, 39, 57, 61],
        [75, 54, 47, 20, 63, 84, 98, 30],
        [25, 66, 11, 91, 90, 39, 43, 65],
        [55, 25, 80, 70, 99, 61, 16, 70],
        [27, 77, 46, 11, 70, 62, 32, 86],
        [58, 43, 26, 27, 45, 32, 98, 67]],

       [[ 1, 11, 23, 14, 50, 33, 98, 73],
        [66, 13, 67, 13, 39, 45, 46, 51],
        [27, 86, 90, 99, 52, 59, 58, 60],
        [81, 62, 88, 38, 28, 21, 18, 31],
        [84, 18, 20, 51, 40, 57,  7, 69],
        [79, 80, 81, 26, 19, 53, 12,  3]],

       [[57, 10, 73, 30, 19, 80, 84, 34],
        [69, 86, 70, 12, 37,  2, 14, 49],
        [ 5, 43, 24, 88, 82, 14, 96, 33],
        [33, 14, 67, 50, 18, 71, 57, 88],
        [79, 33,  2, 

In [13]:
# Collect the grades of the 3rd and 5th subjects of all students
tf.gather(x,[2,4],axis=2)

<tf.Tensor: shape=(4, 35, 2), dtype=int32, numpy=
array([[[ 9, 10],
        [17, 94],
        [73, 45],
        [67, 33],
        [92, 53],
        [34, 89],
        [26, 54],
        [19, 99],
        [85,  0],
        [99, 41],
        [ 1, 75],
        [76, 60],
        [32, 12],
        [26, 64],
        [ 9, 10],
        [62, 55],
        [60, 13],
        [56, 50],
        [54, 18],
        [65, 98],
        [13, 72],
        [80, 75],
        [ 2, 52],
        [24, 58],
        [ 1, 93],
        [96, 24],
        [42, 22],
        [76, 90],
        [98, 32],
        [96, 82],
        [ 4, 45],
        [48, 95],
        [81, 48],
        [58,  7],
        [13, 19]],

       [[75, 50],
        [ 8, 65],
        [90, 13],
        [47, 63],
        [54, 51],
        [78, 95],
        [55, 93],
        [34, 48],
        [11, 90],
        [80,  5],
        [69, 39],
        [80, 99],
        [46, 70],
        [37, 47],
        [13, 37],
        [52, 30],
        [ 6, 14],
        [34,

In [14]:
a=tf.range(8)
a

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int32)>

In [15]:
a=tf.reshape(a,[4,2])
a

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]], dtype=int32)>

In [16]:
tf.gather(a,[3,1,0,2],axis=0) # Collect element 4,2,1,3

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[6, 7],
       [2, 3],
       [0, 1],
       [4, 5]], dtype=int32)>

In [17]:
#tf.gather_nd
tf.gather_nd(x,[[1,1],[2,2],[3,3]])

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[86, 73,  8, 33, 65, 34, 58, 49],
       [61, 54, 28,  9, 64,  9, 38, 38],
       [69, 86, 70, 12, 37,  2, 14, 49]], dtype=int32)>

In [18]:
tf.gather_nd(x,[[1,1,2],[2,2,3],[3,3,4]])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 8,  9, 37], dtype=int32)>