<a href="https://colab.research.google.com/github/SindhuraShankeshi/colab/blob/main/MathematicalOps.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import tensorflow as tf

In [20]:
x=tf.range(96)
x

<tf.Tensor: shape=(96,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95], dtype=int32)>

In [21]:
x=tf.reshape(x,[4,2,4,3])
x

<tf.Tensor: shape=(4, 2, 4, 3), dtype=int32, numpy=
array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]]],


       [[[24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44],
         [45, 46, 47]]],


       [[[48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]]],


       [[[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80],
         [81, 82, 83]],

        [[84, 85, 86],
         [87, 88, 89],
         [90, 91, 92],
         [93, 94, 95]]]], dtype=int32)>

In [22]:
x.ndim,x.shape

(4, TensorShape([4, 2, 4, 3]))

In [23]:
 tf.reshape(x,[2,-1,3])

<tf.Tensor: shape=(2, 16, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44],
        [45, 46, 47]],

       [[48, 49, 50],
        [51, 52, 53],
        [54, 55, 56],
        [57, 58, 59],
        [60, 61, 62],
        [63, 64, 65],
        [66, 67, 68],
        [69, 70, 71],
        [72, 73, 74],
        [75, 76, 77],
        [78, 79, 80],
        [81, 82, 83],
        [84, 85, 86],
        [87, 88, 89],
        [90, 91, 92],
        [93, 94, 95]]], dtype=int32)>

In [24]:
tf.reshape(x,[2,-1])

<tf.Tensor: shape=(2, 48), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]],
      dtype=int32)>

In [25]:
#adding dimensions
add=tf.random.uniform([28,28],maxval=10,dtype=tf.int64)
add

<tf.Tensor: shape=(28, 28), dtype=int64, numpy=
array([[5, 3, 7, 6, 8, 7, 8, 3, 0, 3, 6, 3, 1, 4, 0, 6, 1, 2, 3, 4, 6, 1,
        3, 7, 7, 2, 3, 8],
       [7, 2, 4, 8, 8, 9, 5, 7, 0, 3, 2, 4, 6, 9, 7, 9, 7, 9, 7, 9, 8, 8,
        5, 3, 2, 6, 1, 5],
       [0, 7, 9, 5, 8, 2, 4, 5, 2, 6, 8, 5, 6, 0, 0, 4, 3, 3, 3, 5, 3, 4,
        7, 0, 3, 4, 3, 9],
       [8, 1, 3, 5, 0, 5, 8, 3, 4, 0, 9, 6, 6, 1, 5, 9, 0, 9, 3, 1, 3, 2,
        9, 3, 0, 3, 7, 5],
       [1, 5, 8, 8, 4, 1, 1, 0, 2, 3, 0, 8, 9, 7, 4, 4, 1, 6, 1, 6, 0, 1,
        1, 7, 6, 0, 2, 7],
       [0, 8, 3, 6, 9, 8, 3, 1, 2, 8, 6, 8, 1, 3, 2, 2, 8, 5, 3, 1, 7, 5,
        6, 0, 3, 3, 2, 6],
       [2, 3, 0, 7, 0, 0, 7, 9, 3, 5, 8, 4, 2, 5, 5, 3, 9, 6, 7, 7, 2, 9,
        4, 6, 5, 7, 9, 7],
       [5, 7, 6, 6, 6, 4, 7, 8, 0, 7, 2, 5, 0, 8, 5, 7, 8, 0, 3, 5, 6, 7,
        0, 6, 0, 2, 1, 6],
       [4, 2, 6, 4, 6, 6, 7, 0, 0, 5, 8, 8, 3, 2, 3, 5, 6, 3, 1, 8, 1, 2,
        5, 5, 0, 6, 5, 0],
       [8, 6, 2, 0, 5, 7, 9, 9, 8, 2, 9, 9,

In [26]:
add=tf.expand_dims(add,axis=1)
add

<tf.Tensor: shape=(28, 1, 28), dtype=int64, numpy=
array([[[5, 3, 7, 6, 8, 7, 8, 3, 0, 3, 6, 3, 1, 4, 0, 6, 1, 2, 3, 4, 6,
         1, 3, 7, 7, 2, 3, 8]],

       [[7, 2, 4, 8, 8, 9, 5, 7, 0, 3, 2, 4, 6, 9, 7, 9, 7, 9, 7, 9, 8,
         8, 5, 3, 2, 6, 1, 5]],

       [[0, 7, 9, 5, 8, 2, 4, 5, 2, 6, 8, 5, 6, 0, 0, 4, 3, 3, 3, 5, 3,
         4, 7, 0, 3, 4, 3, 9]],

       [[8, 1, 3, 5, 0, 5, 8, 3, 4, 0, 9, 6, 6, 1, 5, 9, 0, 9, 3, 1, 3,
         2, 9, 3, 0, 3, 7, 5]],

       [[1, 5, 8, 8, 4, 1, 1, 0, 2, 3, 0, 8, 9, 7, 4, 4, 1, 6, 1, 6, 0,
         1, 1, 7, 6, 0, 2, 7]],

       [[0, 8, 3, 6, 9, 8, 3, 1, 2, 8, 6, 8, 1, 3, 2, 2, 8, 5, 3, 1, 7,
         5, 6, 0, 3, 3, 2, 6]],

       [[2, 3, 0, 7, 0, 0, 7, 9, 3, 5, 8, 4, 2, 5, 5, 3, 9, 6, 7, 7, 2,
         9, 4, 6, 5, 7, 9, 7]],

       [[5, 7, 6, 6, 6, 4, 7, 8, 0, 7, 2, 5, 0, 8, 5, 7, 8, 0, 3, 5, 6,
         7, 0, 6, 0, 2, 1, 6]],

       [[4, 2, 6, 4, 6, 6, 7, 0, 0, 5, 8, 8, 3, 2, 3, 5, 6, 3, 1, 8, 1,
         2, 5, 5, 0, 6, 5, 0]],

    

In [31]:
 add=tf.squeeze(add, axis=1) 
 add

<tf.Tensor: shape=(28, 28), dtype=int64, numpy=
array([[5, 3, 7, 6, 8, 7, 8, 3, 0, 3, 6, 3, 1, 4, 0, 6, 1, 2, 3, 4, 6, 1,
        3, 7, 7, 2, 3, 8],
       [7, 2, 4, 8, 8, 9, 5, 7, 0, 3, 2, 4, 6, 9, 7, 9, 7, 9, 7, 9, 8, 8,
        5, 3, 2, 6, 1, 5],
       [0, 7, 9, 5, 8, 2, 4, 5, 2, 6, 8, 5, 6, 0, 0, 4, 3, 3, 3, 5, 3, 4,
        7, 0, 3, 4, 3, 9],
       [8, 1, 3, 5, 0, 5, 8, 3, 4, 0, 9, 6, 6, 1, 5, 9, 0, 9, 3, 1, 3, 2,
        9, 3, 0, 3, 7, 5],
       [1, 5, 8, 8, 4, 1, 1, 0, 2, 3, 0, 8, 9, 7, 4, 4, 1, 6, 1, 6, 0, 1,
        1, 7, 6, 0, 2, 7],
       [0, 8, 3, 6, 9, 8, 3, 1, 2, 8, 6, 8, 1, 3, 2, 2, 8, 5, 3, 1, 7, 5,
        6, 0, 3, 3, 2, 6],
       [2, 3, 0, 7, 0, 0, 7, 9, 3, 5, 8, 4, 2, 5, 5, 3, 9, 6, 7, 7, 2, 9,
        4, 6, 5, 7, 9, 7],
       [5, 7, 6, 6, 6, 4, 7, 8, 0, 7, 2, 5, 0, 8, 5, 7, 8, 0, 3, 5, 6, 7,
        0, 6, 0, 2, 1, 6],
       [4, 2, 6, 4, 6, 6, 7, 0, 0, 5, 8, 8, 3, 2, 3, 5, 6, 3, 1, 8, 1, 2,
        5, 5, 0, 6, 5, 0],
       [8, 6, 2, 0, 5, 7, 9, 9, 8, 2, 9, 9,