<a href="https://colab.research.google.com/github/SindhuraShankeshi/colab/blob/main/T2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [25]:
#indexing
out=tf.random.uniform([4,10])
y=tf.constant([2,3,2,0])
y=tf.one_hot(y,depth=10)
y

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [22]:
loss=tf.keras.losses.mse(y,out)
loss=tf.reduce_mean(loss)
loss

<tf.Tensor: shape=(), dtype=float32, numpy=0.35990843>

In [24]:
#suppose z is the output of an activation function
z=tf.random.normal([4,2])
b=tf.zeros([2])
z=z+b
z

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[-0.91305596, -1.2042917 ],
       [ 0.9609559 ,  0.03918292],
       [ 1.2008027 ,  1.0314838 ],
       [ 0.3382336 ,  0.6642151 ]], dtype=float32)>

In [28]:
#matrix
w=tf.ones([4,3])
b=tf.zeros([3])
o=x@w+b
o

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.39456546, 0.39456546, 0.39456546],
       [0.9113765 , 0.9113765 , 0.9113765 ]], dtype=float32)>

In [6]:
x = tf.random.normal ([4,32,32,3])
x[0]

<tf.Tensor: shape=(32, 32, 3), dtype=float32, numpy=
array([[[-0.22918552,  2.138211  , -0.9252853 ],
        [ 0.7022873 , -0.8273759 ,  0.9728179 ],
        [ 0.98519385, -0.6133142 , -0.7403481 ],
        ...,
        [ 0.6950395 ,  1.289417  ,  0.7134231 ],
        [ 1.5493052 ,  0.54882073,  0.49382827],
        [ 1.9354402 ,  0.41408587,  0.74462175]],

       [[ 0.16149563, -0.9529151 , -1.6215318 ],
        [-1.668102  , -0.38166526, -0.32253814],
        [ 0.21224417, -0.8902501 , -0.1198384 ],
        ...,
        [ 0.33048368, -1.6256756 , -0.5441219 ],
        [ 1.605591  , -1.3270358 , -0.87322396],
        [-1.989421  ,  0.45762962, -0.7278316 ]],

       [[-0.9996816 ,  1.6064891 , -0.3956453 ],
        [-0.90508443, -0.2729873 ,  0.06297436],
        [-1.8336579 ,  1.0576532 , -0.6981616 ],
        ...,
        [-0.2330587 , -1.0982398 ,  0.10993331],
        [-1.269449  ,  1.3507874 , -0.55980456],
        [-1.01417   ,  1.2276838 ,  0.12976734]],

       ...,

       

In [7]:
x[0][1]


<tf.Tensor: shape=(32, 3), dtype=float32, numpy=
array([[ 0.16149563, -0.9529151 , -1.6215318 ],
       [-1.668102  , -0.38166526, -0.32253814],
       [ 0.21224417, -0.8902501 , -0.1198384 ],
       [-0.8324853 , -0.1321395 , -0.7993788 ],
       [-0.71382   , -1.0429    , -0.24457832],
       [ 0.35673085, -0.4186411 ,  0.39735943],
       [ 0.388216  , -1.4688929 ,  0.5617945 ],
       [-0.48657537,  0.8766469 , -1.8415586 ],
       [-0.12473849,  0.7956474 , -0.9969268 ],
       [ 0.0342369 ,  0.6510029 , -0.16457911],
       [-0.14459874,  0.43605322, -1.2208196 ],
       [-1.7731047 , -1.3634194 , -0.12361582],
       [-0.62370974, -0.0302579 , -1.392132  ],
       [-1.1078862 , -0.56935215, -2.6312366 ],
       [ 1.9117886 ,  0.99319774,  0.4116318 ],
       [-0.20761055, -0.9187877 ,  1.4536879 ],
       [ 0.6301691 ,  0.20226164, -1.0439357 ],
       [-0.00861838,  1.958624  ,  0.47192046],
       [-0.2543204 , -0.7740156 , -0.31030974],
       [ 1.0177015 ,  0.09296563,  0.32

In [8]:
x[2][1][0][1]

<tf.Tensor: shape=(), dtype=float32, numpy=0.43778482>

In [9]:
#slicing
x[1:3]

<tf.Tensor: shape=(2, 32, 32, 3), dtype=float32, numpy=
array([[[[ 1.632553  , -2.0060792 , -1.5925547 ],
         [-1.2629447 , -1.9555019 ,  1.1694661 ],
         [ 1.8103065 ,  0.9924158 , -0.09163488],
         ...,
         [-1.1506262 , -0.8300852 , -1.0706705 ],
         [-0.6783774 , -0.27732116, -0.03743636],
         [-0.09417905, -0.45616418,  0.2939853 ]],

        [[-0.13424769, -2.329324  ,  0.697506  ],
         [-1.1837521 ,  0.8772612 ,  0.5631042 ],
         [ 1.2653514 , -0.64743197, -1.414108  ],
         ...,
         [-0.27896   ,  0.44733506, -0.25474122],
         [-0.9809196 , -0.73327005,  0.5092174 ],
         [-0.08213258,  1.3815582 , -0.12878117]],

        [[-0.8161821 , -1.154804  ,  0.33687055],
         [-1.5240685 ,  0.10432275, -2.0506353 ],
         [-1.2069376 , -0.24292582,  0.14312865],
         ...,
         [-2.3036978 , -0.5267907 , -0.42370626],
         [-0.13338287, -0.3642424 ,  0.9022588 ],
         [ 0.49744263,  0.30467814, -1.4666244 ]

In [10]:
x[0,::] 

<tf.Tensor: shape=(32, 32, 3), dtype=float32, numpy=
array([[[-0.22918552,  2.138211  , -0.9252853 ],
        [ 0.7022873 , -0.8273759 ,  0.9728179 ],
        [ 0.98519385, -0.6133142 , -0.7403481 ],
        ...,
        [ 0.6950395 ,  1.289417  ,  0.7134231 ],
        [ 1.5493052 ,  0.54882073,  0.49382827],
        [ 1.9354402 ,  0.41408587,  0.74462175]],

       [[ 0.16149563, -0.9529151 , -1.6215318 ],
        [-1.668102  , -0.38166526, -0.32253814],
        [ 0.21224417, -0.8902501 , -0.1198384 ],
        ...,
        [ 0.33048368, -1.6256756 , -0.5441219 ],
        [ 1.605591  , -1.3270358 , -0.87322396],
        [-1.989421  ,  0.45762962, -0.7278316 ]],

       [[-0.9996816 ,  1.6064891 , -0.3956453 ],
        [-0.90508443, -0.2729873 ,  0.06297436],
        [-1.8336579 ,  1.0576532 , -0.6981616 ],
        ...,
        [-0.2330587 , -1.0982398 ,  0.10993331],
        [-1.269449  ,  1.3507874 , -0.55980456],
        [-1.01417   ,  1.2276838 ,  0.12976734]],

       ...,

       

In [12]:
#reverse slicing
x = tf.range(9) 
x[8:0:-1] 

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([8, 7, 6, 5, 4, 3, 2, 1], dtype=int32)>

In [13]:
 x[::-1]

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([8, 7, 6, 5, 4, 3, 2, 1, 0], dtype=int32)>

In [14]:
x[::-2]


<tf.Tensor: shape=(5,), dtype=int32, numpy=array([8, 6, 4, 2, 0], dtype=int32)>

In [15]:
x = tf.random.normal([4,32,32,3])
x[0,::-2,::-2]

<tf.Tensor: shape=(16, 16, 3), dtype=float32, numpy=
array([[[-2.3470554 , -0.3425965 , -0.01862943],
        [-1.381703  ,  0.8486615 , -1.4249552 ],
        [ 0.69921076,  0.56979007,  1.2043347 ],
        [ 0.25830203,  1.9865836 , -1.05369   ],
        [-2.2135644 , -0.8375737 ,  1.2448918 ],
        [ 1.4429076 ,  0.22549374, -0.6746706 ],
        [ 0.04469673, -1.4218992 ,  0.10232439],
        [ 1.0719507 ,  2.1630447 , -0.2844017 ],
        [-0.4105079 , -0.35878327,  0.7208943 ],
        [ 0.9015383 , -1.9078002 ,  0.46425512],
        [ 0.3438395 ,  0.7072554 , -1.1350341 ],
        [-2.6180723 ,  0.63641626,  0.5704975 ],
        [-0.88531286, -0.16690165,  1.0942475 ],
        [ 1.3093894 ,  0.384683  , -1.8051991 ],
        [-1.5550683 ,  0.6806423 , -2.1452484 ],
        [ 0.95141506,  2.0045311 ,  1.4819565 ]],

       [[ 0.5023232 , -0.82442844,  0.5369498 ],
        [ 1.0220151 ,  1.1168035 ,  1.6837513 ],
        [ 0.42063156,  0.05502179,  1.182404  ],
        [ 1.39

In [16]:
 x[...,:2]

<tf.Tensor: shape=(4, 32, 32, 2), dtype=float32, numpy=
array([[[[ 1.3121191e+00, -9.2345190e-01],
         [ 4.5450449e-01, -4.3704411e-01],
         [-1.5095094e+00, -1.0643269e-01],
         ...,
         [-8.1891680e-01,  4.8910955e-01],
         [-6.5815604e-01, -7.7612746e-01],
         [-1.1678200e+00,  1.8327309e-01]],

        [[ 1.4898503e+00, -5.0569278e-01],
         [-8.9943871e-02, -9.8531507e-02],
         [-1.5487280e-01,  6.0664135e-01],
         ...,
         [-8.5653907e-01,  2.1415821e-01],
         [-5.3568178e-01,  1.2709397e-01],
         [-4.9637800e-01,  3.6673114e-01]],

        [[ 3.0609417e-01, -1.0338085e+00],
         [ 3.7546548e-01,  6.6307706e-01],
         [ 9.7042102e-01,  5.2471691e-01],
         ...,
         [-1.2643409e+00,  1.2534126e+00],
         [-1.6336848e-01,  2.7270898e-01],
         [ 1.1121860e+00, -7.0226294e-01]],

        ...,

        [[-1.7828796e+00,  2.2707273e-01],
         [-3.3801019e-02, -2.6126966e-01],
         [-7.0504916e-