<a href="https://colab.research.google.com/github/SindhuraShankeshi/colab/blob/main/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np
a=tf.constant(1.2)
print(a)
b=tf.constant("hello world")
print(b)
c=tf.constant([1.2,3.2,6.5])
print(c)
d=tf.constant(np.pi, dtype=tf.float32)
print(d)
e=tf.constant(False)
print(e)

tf.Tensor(1.2, shape=(), dtype=float32)
tf.Tensor(b'hello world', shape=(), dtype=string)
tf.Tensor([1.2 3.2 6.5], shape=(3,), dtype=float32)
tf.Tensor(3.1415927, shape=(), dtype=float32)
tf.Tensor(False, shape=(), dtype=bool)


In [ ]:
import tensorflow as tf
a=tf.Variable([1.2,.32,.32])
print(a)

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1.2 , 0.32, 0.32], dtype=float32)>


In [ ]:
import tensorflow as tf
a=tf.convert_to_tensor(np.array([1,2,3,4]))
print(a)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)


In [ ]:
import tensorflow as tf
a=tf.zeros([2,2])
print(a)
a=tf.ones([2,2])
print(a)

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [ ]:
import tensorflow as tf
a=tf.zeros([2,2])
print(a)
a=tf.ones([2,2])
print(a)

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [ ]:
import tensorflow as tf
a=tf.fill([1,2], 100)
print(a)

tf.Tensor([[100 100]], shape=(1, 2), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.random.normal([2,2])
print(a)
a=tf.random.normal([2,2], mean=10, stddev=5)
print(a)

tf.Tensor(
[[ 1.5072289 -0.6402206]
 [-1.2873403  1.2812856]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[11.3834915  6.191373 ]
 [ 9.898272   4.0968156]], shape=(2, 2), dtype=float32)


In [ ]:
import tensorflow as tf
a=tf.random.uniform([2,2])
print(a)
a=tf.random.uniform([2,2], maxval=456, dtype=tf.int32)
print(a)

tf.Tensor(
[[0.00169575 0.6690422 ]
 [0.7874224  0.2627523 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[285 148]
 [386 289]], shape=(2, 2), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.range(5)
print(a)
a=tf.range(10, delta=3)
print(a)
a=tf.range(1,10,delta=5)
print(a)

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)
tf.Tensor([0 3 6 9], shape=(4,), dtype=int32)
tf.Tensor([1 6], shape=(2,), dtype=int32)


In [ ]:
import tensorflow as tf
out=tf.random.uniform([4,10])
print(out)
y=tf.constant([2,3,2,0])
print(y)
y=tf.one_hot(y, depth=10)
print(y)
loss=tf.keras.losses.mse(y, out)
print(loss)
loss=tf.reduce_mean(loss)
print(loss)

tf.Tensor(
[[0.6254883  0.14033604 0.12124288 0.21660912 0.18676937 0.6955571
  0.29395235 0.09032238 0.38218546 0.19544601]
 [0.5766585  0.3850621  0.8225874  0.6393522  0.6040032  0.31567955
  0.68405485 0.91151357 0.7762375  0.2585684 ]
 [0.99289215 0.38128233 0.4921837  0.9523934  0.01055086 0.5638852
  0.9401541  0.3529035  0.9329032  0.26056015]
 [0.546015   0.28070676 0.6747359  0.8888624  0.00301003 0.69091666
  0.6090064  0.8253888  0.48969424 0.5099218 ]], shape=(4, 10), dtype=float32)
tf.Tensor([2 3 2 0], shape=(4,), dtype=int32)
tf.Tensor(
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(4, 10), dtype=float32)
tf.Tensor([0.20275769 0.37201884 0.45608503 0.35595948], shape=(4,), dtype=float32)
tf.Tensor(0.34670526, shape=(), dtype=float32)


In [ ]:
import tensorflow as tf
a=tf.random.normal([3,3])
print(a)
b=tf.ones([3])
print(b)
print(a+b)

tf.Tensor(
[[ 0.51273626 -0.31226388  0.11204689]
 [-0.16071549  0.59211075 -2.7941232 ]
 [-0.00561081 -0.26411554  0.16538672]], shape=(3, 3), dtype=float32)
tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32)
tf.Tensor(
[[ 1.5127363   0.68773615  1.1120468 ]
 [ 0.83928454  1.5921108  -1.7941232 ]
 [ 0.9943892   0.7358844   1.1653867 ]], shape=(3, 3), dtype=float32)


In [ ]:
import tensorflow as tf
a=tf.random.uniform([2,2])
b=tf.zeros([2,2])
c=tf.ones([2,2])
print(a@b+c)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [ ]:
import tensorflow as tf
x=tf.random.normal([4,32,32,3]) # 4 images 32*32 pixels each pixel 3 values
print(x)
print(x[0][1][2]) # 0th image 0th row 2nd col 

tf.Tensor(
[[[[ 4.08951610e-01 -5.45497656e-01 -5.25506325e-02]
   [-1.11508799e+00  1.35048062e-01 -2.65283197e-01]
   [ 2.68119335e-01  1.40142000e+00 -1.48697209e+00]
   ...
   [ 1.39640021e+00  3.29776257e-01  8.41126621e-01]
   [ 5.52806258e-01  2.60544372e+00  1.39818859e+00]
   [-1.22690320e-01 -6.95493221e-01  5.51843584e-01]]

  [[ 1.20613027e+00  9.98574197e-01 -1.33174613e-01]
   [ 1.56130657e-01 -1.75567758e+00 -1.87850845e+00]
   [ 9.04752135e-01  7.60453522e-01 -1.57283306e-01]
   ...
   [-5.85957915e-02  9.40635800e-01 -1.18450534e+00]
   [ 4.36437011e-01  8.16004574e-01 -9.74604428e-01]
   [ 1.17737389e+00 -1.36478889e+00 -1.58202574e-01]]

  [[-1.03883195e+00 -3.14561397e-01  1.72869474e-01]
   [ 1.67603946e+00 -8.54462087e-01 -1.19191122e+00]
   [ 1.47833422e-01  5.20803988e-01  3.33041072e-01]
   ...
   [ 1.55293620e+00  2.60477573e-01 -1.98266363e+00]
   [ 1.93252057e-01  1.42096972e+00 -2.64236689e-01]
   [-1.31531453e+00  6.21747077e-02  4.33795780e-01]]

  ...

 

In [ ]:
import tensorflow as tf
# start:end:step Read from “start” to “end” (excluding) with step length of “step.”
# start:end Read from “start” to “end” (excluding) with step length of 1.
# start: Read from “start” to the end of object with step length of 1.
# start::step Read from “start” to the end of object with step length of “step.”
# :end:step Read from the 0th item to “end” (excluding) with step length of “step.”
# :end Read from 0th item to “end” (excluding) with step length of 1.
# ::step Read from 0th item to the last item with step length of “step.”
# :: Read all items.
# : Read all items
x=tf.random.normal([3,3])
print(x[::])

tf.Tensor(
[[ 1.3391551  -0.04859175 -2.1052139 ]
 [ 1.9858811  -0.5018503   1.0182652 ]
 [-0.893274    0.79782635 -0.2149153 ]], shape=(3, 3), dtype=float32)


In [ ]:
import tensorflow as tf
# a,⋯,b Select 0 to a for dimension a, b to end for dimension b, and all elements 
# for other dimensions.
# a,⋯ Select 0 to a for dimension a and all elements for other dimensions.
# ⋯,b Select b to end for dimension b and all elements for other dimensions.
# ⋯ Read all elements.
x=tf.random.normal([3,3])
print(x[...])

tf.Tensor(
[[-0.7980877  -1.3078605   1.1941855 ]
 [ 0.19867878 -0.13885738  0.27221322]
 [ 0.375359    0.4585931  -1.0983262 ]], shape=(3, 3), dtype=float32)


In [ ]:
import tensorflow as tf
x=tf.range(10)
print(x)
x=tf.reshape(x, [2,5])
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor(
[[0 1 2 3 4]
 [5 6 7 8 9]], shape=(2, 5), dtype=int32)


In [ ]:
import tensorflow as tf
x=tf.random.uniform([5,5],maxval=10,dtype=tf.int32)
print(x)
x=tf.expand_dims(x, axis=1)
print(x)
x=tf.squeeze(x, axis=1)
print(x)

tf.Tensor(
[[8 9 1 4 3]
 [0 6 0 5 3]
 [6 4 3 6 6]
 [9 2 6 7 3]
 [7 8 8 5 2]], shape=(5, 5), dtype=int32)
tf.Tensor(
[[[8 9 1 4 3]]

 [[0 6 0 5 3]]

 [[6 4 3 6 6]]

 [[9 2 6 7 3]]

 [[7 8 8 5 2]]], shape=(5, 1, 5), dtype=int32)
tf.Tensor(
[[8 9 1 4 3]
 [0 6 0 5 3]
 [6 4 3 6 6]
 [9 2 6 7 3]
 [7 8 8 5 2]], shape=(5, 5), dtype=int32)


In [ ]:
import tensorflow as tf
x=tf.random.uniform([2,4])
print(x)
x=tf.transpose(x, perm=[1,0])
print(x)

tf.Tensor(
[[0.14525664 0.8481531  0.23620391 0.7944852 ]
 [0.35636652 0.465423   0.8993703  0.8069091 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[0.14525664 0.35636652]
 [0.8481531  0.465423  ]
 [0.23620391 0.8993703 ]
 [0.7944852  0.8069091 ]], shape=(4, 2), dtype=float32)


In [ ]:
import tensorflow as tf
x=tf.constant([[1,2]])
print(x)
y=tf.tile(x, multiples=[2,1])
print(y)
z=tf.tile(x, multiples=[1,2])
print(z)

tf.Tensor([[1 2]], shape=(1, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [1 2]], shape=(2, 2), dtype=int32)
tf.Tensor([[1 2 1 2]], shape=(1, 4), dtype=int32)
